export const destinationCatalog=[
{id:'mara',name:'Mara & the Living Savannah',region:'Kenya',country:'Kenya',type:'Wildlife',icon:'🦁',lat:-1.49,lng:35.14,season:'Jul–Oct',mood:'Expansive',desc:'Conservation-led game drives, open skies and migration landscapes.',story:'A grassland system shaped by rainfall, grazers, predators and generations of pastoral stewardship.',highlights:['Dawn game drives','Community-led cultural encounters','Conservation storytelling','Night-sky sessions'],image:'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1400&q=80'},
{id:'rift',name:'The Great Rift',region:'East Africa',country:'Kenya',type:'Origins',icon:'⛰️',lat:-0.5,lng:36.1,season:'Year-round',mood:'Ancient',desc:'Volcanic escarpments, lakes and the geological story of our planet.',story:'Read tectonic time in escarpments, volcanic landforms and lake basins while connecting geology with human history.',highlights:['Geology walks','Cradle-of-humanity interpretation','Lake landscapes','Volcanic viewpoints'],image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=80'},
{id:'coast',name:'Rivers & Coast',region:'East Africa',country:'Kenya',type:'Water',icon:'🌊',lat:-4.1,lng:39.4,season:'Jan–Mar · Jul–Oct',mood:'Flow',desc:'Slow journeys through waterways, wetlands and coastal cultures.',story:'Follow water from inland catchments toward mangroves, reefs and centuries-old coastal settlements.',highlights:['Dhow experiences','Mangrove ecology','Swahili heritage','Ocean wellness'],image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80'},
{id:'forest',name:'Canopy & Stillness',region:'East Africa',country:'Kenya',type:'Wellness',icon:'🌿',lat:0.3,lng:34.85,season:'Dec–Mar · Jun–Sep',mood:'Restorative',desc:'Forest immersion, birdsong, biodiversity and restorative retreats.',story:'Move slowly beneath complex forest canopies where biodiversity, water and human wellbeing meet.',highlights:['Forest bathing','Birding','Guided biodiversity walks','Digital-detox sessions'],image:'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1400&q=80'},
{id:'desert',name:'Desert & Deep Time',region:'Northern Kenya',country:'Kenya',type:'Origins',icon:'☀️',lat:2.8,lng:36.7,season:'Jun–Sep',mood:'Stillness',desc:'Stargazing, archaeological heritage and the beauty of silence.',story:'A journey through arid landscapes, immense skies and evidence of environmental and human change across deep time.',highlights:['Dark-sky stargazing','Desert geology','Archaeological interpretation','Slow overland travel'],image:'https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1400&q=80'},
{id:'river',name:'Great River Journeys',region:'East Africa',country:'Regional',type:'Water',icon:'🏞️',lat:-1.0,lng:33.0,season:'Route dependent',mood:'Elemental',desc:'Expedition concepts following the arteries that sustain landscapes and communities.',story:'Understand how rivers connect highlands, wetlands, wildlife, farms and settlements across vast watersheds.',highlights:['Watershed interpretation','Wetland wildlife','Community encounters','Photography'],image:'https://images.unsplash.com/photo-1437482078695-73f5ca6c96e2?auto=format&fit=crop&w=1400&q=80'}
];
export const experienceModes=[
{title:'AI Journey Designer',status:'Prototype',copy:'Preference-led route concepts combining landscape, pace, interests and budget.'},
{title:'3D Digital Landscapes',status:'Concept',copy:'Interactive terrain and destination twins for pre-trip exploration.'},
{title:'Living Wildlife',status:'Partner data required',copy:'Ethically sourced cameras and verified wildlife observations when partnerships are established.'},
{title:'Origins & Deep Time',status:'Curated',copy:'Geology, archaeology and human-origins interpretation designed for curious travellers.'},
{title:'Grounded Wellness',status:'Curated',copy:'Forest, water, desert, silence, movement and restorative travel.'},
{title:'Biodiversity Passport',status:'Prototype',copy:'Log responsibly observed species and landscapes without exposing sensitive locations.'}
];