import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{BrowserRouter,Link,Route,Routes}from'react-router-dom';
import{Canvas}from'@react-three/fiber';
import{OrbitControls,Stars}from'@react-three/drei';
import{Compass,Leaf,Waves,Mountain,Sun,LogIn,LogOut,Sparkles,Send}from'lucide-react';
import{onAuthStateChanged,signInWithPopup,signOut}from'firebase/auth';
import{addDoc,collection,serverTimestamp}from'firebase/firestore';
import{auth,db,configured,googleProvider}from'./firebase';import{ensureProfile}from'./services';import{ensureProfile}from'./services';
import Destination from './Destination';import Dashboard from './Dashboard';import Planner from './Planner';import Admin from './Admin';import Integrations from './Integrations';import Planner from './Planner';import Admin from './Admin';import{destinationCatalog as destinations,experienceModes}from'./data';import './style.css';
function Earth(){return <div className="earth" aria-label="Interactive stylized 3D Earth"><Canvas camera={{position:[0,0,4.2]}}><ambientLight intensity={1.4}/><directionalLight position={[4,2,5]} intensity={2}/><mesh rotation={[.3,.1,.2]}><sphereGeometry args={[1.4,48,48]}/><meshStandardMaterial color="#5e7959" roughness={.95} wireframe/></mesh><mesh><sphereGeometry args={[1.38,40,40]}/><meshStandardMaterial color="#132e28" metalness={.1} roughness={.8}/></mesh><Stars radius={30} depth={30} count={700} factor={2} fade/><OrbitControls enableZoom={false} autoRotate autoRotateSpeed={.5}/></Canvas><span className="earth-caption">Explore our planet • interactive conceptual globe</span></div>}
function App(){const[user,setUser]=useState(null);const[notice,setNotice]=useState('');const[interest,setInterest]=useState('All');const[budget,setBudget]=useState('');const[days,setDays]=useState('5');const[trip,setTrip]=useState([]);const[message,setMessage]=useState('');useEffect(()=>auth?onAuthStateChanged(auth,u=>{setUser(u);if(u)ensureProfile(u).catch(()=>{})}):undefined,[]);
const filtered=interest==='All'?destinations:destinations.filter(d=>d.type===interest);
function plan(){const pool=filtered.length?filtered:destinations;setTrip(Array.from({length:Math.min(14,Math.max(1,Number(days)||5))},(_,i)=>pool[i%pool.length]));setNotice('Sample itinerary generated locally. Pricing, travel time and availability must be confirmed with an operator.');}
async function inquiry(e){e.preventDefault();if(!db){setNotice('Firebase is not configured. Set your environment variables before submitting.');return;}if(!user){setNotice('Please sign in to submit your inquiry.');return;}try{await addDoc(collection(db,'inquiries'),{userId:user.uid,displayName:user.displayName||'',email:user.email||'',message:message.slice(0,2000),interest,budget:budget.slice(0,50),days:Number(days),createdAt:serverTimestamp(),status:'new'});setNotice('Inquiry submitted successfully.');setMessage('');}catch{setNotice('Could not submit. Check permissions and try again.');}}
async function login(){if(!auth){setNotice('Firebase is not configured yet.');return;}try{await signInWithPopup(auth,googleProvider);}catch{setNotice('Sign-in did not complete.');}}
return <><header><Link to="/" className="brand"><span className="brandmark">W</span><span>WILD <strong>RYFTLANDS</strong><small>JOURNEY INTO ORIGINS</small></span></Link><nav><a href="/#explore">Explore</a><a href="/#experiences">Experiences</a><Link to="/plan">Plan a journey</Link><Link to="/about">Our ethos</Link><Link to="/me">My Ryftlands</Link></nav><button className="login" onClick={()=>user?signOut(auth):login()}>{user?<><LogOut size={16}/> Sign out</>:<><LogIn size={16}/> Sign in</>}</button></header>
{notice&&<div role="status" className="notice">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss">×</button></div>}
<Routes><Route path="/" element={<><section className="hero"><div className="hero-copy"><div className="eyebrow">THE EARTH IS CALLING</div><h1>Return to<br/>the <em>living</em><br/>earth.</h1><p>Journey across ancient rift valleys, untamed savannahs, vast deserts and restorative rainforests. Discover the landscapes that shaped us.</p><div className="actions"><Link className="primary" to="/plan">Design your journey <Compass size={18}/></Link><a className="secondary" href="#explore">Discover the wild ↓</a></div><div className="hero-foot">WILDLIFE · ORIGINS · CONSERVATION · WELLNESS</div></div><Earth/></section><section className="intro" id="experiences"><div className="eyebrow">BEYOND THE ORDINARY</div><h2>Not just a destination.<br/><em>A deeper connection.</em></h2><p>From the cradle of humanity to living conservation landscapes, discover a slower, more meaningful way to travel.</p><div className="pillars">{[[Mountain,'Ancient origins','Walk through geological deep time and human heritage.'],[Leaf,'Living conservation','Respectful encounters that prioritize people and nature.'],[Waves,'Elemental wellness','Reconnect through rivers, forests, deserts and silence.'],[Sun,'Immersive discovery','Explore landscapes and plan with interactive digital tools.']].map(([Icon,title,copy])=><article key={title}><Icon size={26}/><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="explore" id="explore"><div className="section-top"><div><div className="eyebrow">CHOOSE YOUR LANDSCAPE</div><h2>Where will the earth <em>take you?</em></h2></div><Link to="/plan">Create your journey →</Link></div><div className="filters">{['All','Wildlife','Origins','Water','Wellness'].map(x=><button key={x} className={interest===x?'active':''} onClick={()=>setInterest(x)}>{x}</button>)}</div><div className="destinations">{filtered.map(d=><article className="destination" key={d.id}><img src={d.image} alt={d.name} loading="lazy"/><div className="destination-content"><span>{d.icon} {d.type.toUpperCase()} · {d.region}</span><h3>{d.name}</h3><p>{d.desc}</p><Link to={`/destination/${d.id}`}>Explore experience ↗</Link></div></article>)}</div></section><section className="modes"><div className="eyebrow">THE RYFTLANDS LAYER</div><h2>Nature first. <em>Technology in service of wonder.</em></h2><div className="modeGrid">{experienceModes.map(x=><article key={x.title}><span>{x.status}</span><h3>{x.title}</h3><p>{x.copy}</p></article>)}</div></section><section className="banner"><div className="eyebrow">YOUR NEXT CHAPTER</div><h2>Some journeys change<br/>how you see <em>everything.</em></h2><Link className="primary" to="/plan">Start exploring <Compass size={18}/></Link></section></>}/>
<Route path="/plan" element={<Planner user={user} onNotice={setNotice}/>}/>
<Route path="/destination/:id" element={<Destination/>}/><Route path="/admin" element={<Admin user={user} onNotice={setNotice}/>}/><Route path="/admin/integrations" element={<Integrations user={user} onNotice={setNotice}/>}/><Route path="/admin" element={<Admin user={user} onNotice={setNotice}/>}/><Route path="/me" element={<Dashboard user={user}/>}/><Route path="/about" element={<main className="page about"><div className="eyebrow">OUR ETHOS</div><h1>Grounded in <em>the earth.</em></h1><p>Wild Ryftlands is an emerging concept for immersive African travel rooted in wildlife, geological heritage, cultural respect, conservation and restorative experiences.</p><p>We aim to work with qualified local guides and conservation partners. Experiences, live wildlife data and partner commitments will only be published after verification.</p><Link className="primary" to="/plan">Plan a journey →</Link></main>}/></Routes><footer><div className="brand"><span className="brandmark">W</span><span>WILD <strong>RYFTLANDS</strong><small>JOURNEY INTO ORIGINS</small></span></div><p>Ancient landscapes. Living connections.</p><small>© {new Date().getFullYear()} Wild Ryftlands. Concept website.</small></footer></>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
