export const trustLevels={official:{label:'Official',rank:6},partner:{label:'Partner verified',rank:5},guide:{label:'Guide verified',rank:4},traveller:{label:'Traveller reported',rank:3},ai:{label:'AI interpreted',rank:2},archive:{label:'Historical / archival',rank:4}};export const platformModules=[
['Ethical Travel','Wildlife Ethics Score','Reward respectful distance, quiet observation, no feeding and guide compliance.','operational'],
['Impact','Regenerative Travel Score','Transparent itinerary indicators for local spend, conservation contribution and travel practices.','methodology-required'],
['Impact','Carbon Estimator','Estimate transport/accommodation footprint without claiming automatic carbon neutrality.','methodology-required'],
['Science','Citizen Science Export','Review appropriate observations before formatting them for research platforms.','partner-required'],
['Nature','Species Knowledge Graph','Connect species to habitat, sound, tracks, diet, behaviour, ecology, quests and verified records.','data-layer'],
['Nature','Ecological Relationship AR','Reveal ecosystem relationships instead of merely labeling animals.','content-required'],
['Earth','Geology Explorer','Faults, volcanoes, escarpments, rocks, geothermal systems, lakes and deep-time quests.','content-required'],
['Origins','Human Origins Explorer','Verified archaeology, hominin timelines, palaeoenvironments and museum stories.','partner-required'],
['Culture','Food Journey','Regional ingredients, markets, farms and community-controlled culinary stories.','partner-required'],
['Culture','Journey Soundtrack','Licensed region-specific artists and cultural context instead of generic music.','rights-required'],
['Marketplace','Local Creator Marketplace','Verified photographers, artists, musicians, storytellers and craftspeople.','partner-required'],
['Groups','Private Expedition Groups','Shared itinerary, expenses, media, polls, quests and collaborative documentary.','operational'],
['Education','School / University Expeditions','Learning objectives, field observations and post-trip learning reports.','operational'],
['Research','Research Expedition Mode','Permissioned field observations, forms, notes and research team workflows.','governance-required'],
['Service','Premium Expedition Concierge','AI planning with explicit human handoff for logistics, safety and negotiation.','operations-required'],
['Discovery','Surprise Me','Build an expedition from budget, dates, interests and comfort constraints.','planner'],
['Commerce','Expedition Drops','Limited-capacity themed expeditions and special departures.','inventory-required'],
['Identity','Annual Explorer Recap','Yearly exploration, learning, conservation and Story Director recap.','operational'],
['Identity','Legacy Map','Long-term 3D history of explored places and associated stories.','operational'],
['Commerce','Gift / Sponsor an Explorer','Fund trips or educational expeditions with transparent redemption.','payments-required'],
['Partners','Partner Intelligence','Anonymized demand, seasonality, engagement and booking-funnel analytics.','analytics'],
['Platform','Wild Ryftlands API / MCP','Permissioned verified experience, destination and availability interfaces.','future-api']
];